### PR TITLE
Feat: Registration config

### PR DESCRIPTION
**Pull request by nam-t24**
Registration form extracts data from hackportal config file.
Registration config that users change
 - Registration questions
 - stat record types: user chooses which item is displayed in admin stats page and the corresponding type
 - field names: chart titles of the above stat records user wants to be displayed
 - array field/single field: add the chosen fields to the corresponding type(array or single)

### CODE REVIEW

**Comment by DedsecKnight** [comment]
Feel free to resolve this comment if this is already addressed, but it seems like if someone wants to add a new question, they might still need to manually modify the `GeneralStats` object here: https://github.com/acmutd/hackportal/blob/feat/config/lib/types.d.ts#L238

**Review by DedsecKnight — COMMENTED** [review]
Feel free to resolve this comment if this is already addressed, but it seems like if someone wants to add a new question, they might still need to manually modify the `GeneralStats` object here: https://github.com/acmutd/hackportal/blob/feat/config/lib/types.d.ts#L238

**Comment by nam-t24** [comment]
> Feel free to resolve this comment if this is already addressed, but it seems like if someone wants to add a new question, they might still need to manually modify the `GeneralStats` object here: https://github.com/acmutd/hackportal/blob/feat/config/lib/types.d.ts#L238

whoops I forgot about that. I'll take care of that

**Comment by nam-t24** [comment]
Not sure if there is an easier/faster way to determine the types of the desired fields to be shown in admin page but it seems easy enough to change from the config file that the user should not really have a problem

**Comment by abdullah50053** [comment]
I do recommend adding instructions to the top on how to add a question to registration and potential warnings (such as adding all questions before opening up registration to ensure accurate data in admin-side "Stats at a Glance" view).

**Review by DedsecKnight — APPROVED** [review]

**Comment by abdullah50053** [comment]
Also in the `lib/types.d.ts` file you may want to take a look at the Registration type, seems to have some hardcoded values

**Comment by nam-t24** [comment]
> Also in the `lib/types.d.ts` file you may want to take a look at the Registration type, seems to have some hardcoded values

Should we move the whole thing to the config file which puts more editing to editors? Or just delete the type cuz registration type stuff is mostly kinda already done through the config file stuff

**Comment by abdullah50053** [comment]
If you can safely delete that'd be ideal.

**Comment by DedsecKnight** [comment]
If you plan to make breaking changes, I think you might wanna make sure to specify that because other branches may still rely on the old stuffs.

**Review by abdullah50053 — APPROVED** [review]

**Review by DedsecKnight — APPROVED** [review]

**Review by abdullah50053 — APPROVED** [review]

**Pull request merged**
