### PR TITLE
feat: Implemented feature for super admin to crud event database

### LINKED ISSUE #133: [Feature] Add ability for super admin to add calendar events
# Overview

A super admin should have the ability to add calendar events from the admin dashboard. Currently, an organizer must add calendar events manually to the database.

# Proposal

A super admin should have the ability to add calendar events. This functionality should be accessible under the /admin route to super admins only. All calendar event info should be editable by a super admin as well.

The calendar configuration should have the following options:
- Title
- Event type (eg. workshop, sponsor, social)
- Event start time/date
- Event end time/date
- Location
- Any speakers 
- HackerPack Link
- Event description

# Supplemental Information

Screen Shot 2022-06-09 at 6 10 11 PM

### PR DESCRIPTION
**Pull request by DedsecKnight**
resolves #133 

Basically everything that I think necessary to knock #133. Might need to redo ui though.

### CODE REVIEW

**Comment by abdullah50053** [comment]
Add a check for duplicates, multiple events can be created by spamming the "Edit Event" button repeatedly on creation. Also should rename the button to "Add Event" instead of "Edit" when adding a new event.

**Comment by abdullah50053** [comment]
- [ ]  Add Speakers
- [ ] Add Event Type

**Comment by abdullah50053** [comment]
Adding a new event results in a runtime error:
Screen Shot 2022-06-26 at 12 17 06 AM

**Comment by abdullah50053** [comment]
Add a check for if the speaker value is blank then the speaker does not show up as an option, or add an option to delete a speaker:
Screen Shot 2022-07-05 at 9 57 12 PM
Screen Shot 2022-07-05 at 9 57 36 PM

**Comment by abdullah50053** [comment]
Empty speaker name issue persists, with the spotlight speaker text being completely empty if a speaker value is empty:
Screen Shot 2022-07-22 at 12 08 24 AM
Screen Shot 2022-07-22 at 12 10 15 AM

**Comment by abdullah50053** [comment]
Issue persists

> Empty speaker name issue persists, with the spotlight speaker text being completely empty if a speaker value is empty: Screen Shot 2022-07-22 at 12 08 24 AM Screen Shot 2022-07-22 at 12 10 15 AM

**Review by abdullah50053 — APPROVED** [review]

**Review by nam-t24 — APPROVED** [review]

**Pull request merged**
