### PR TITLE
Merge all changes into 1 branch

### PR DESCRIPTION
**Pull request by DedsecKnight**
This PR contains changes made by me in #46 and #48.

### CODE REVIEW

**Comment by WillieCubed** [comment]
#### 📝 Changed routes:


| [**/about/faq**](https://hackportal-jlpyiftuj-acmutd.vercel.app/about/faq) | [**/about**](https://hackportal-jlpyiftuj-acmutd.vercel.app/about) |
|:-:|:-:|
|<a href="https://hackportal-jlpyiftuj-acmutd.vercel.app/about/faq">Screenshot of /about/faq</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/YL0NKYFhFVj6cwZM8yy7DlS9TKLPKcLcZFu8IsoMlHa3lCz18QPRFBVsh2hYSetayHtDaxcr1akLeRWgtJA2FQ.png">(view full size)</a> |<a href="https://hackportal-jlpyiftuj-acmutd.vercel.app/about">Screenshot of /about</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/sAaTU1tQpIG9l6Bo40qiHgr4Vkx47cCYB98nrL2S76NYNWMRgJgngtB7kNsAFI-ASw6higvB03S8Y3rlWo38og.png">(view full size)</a> |



| [**/about/questions**](https://hackportal-jlpyiftuj-acmutd.vercel.app/about/questions) | [**/admin**](https://hackportal-jlpyiftuj-acmutd.vercel.app/admin) |
|:-:|:-:|
|<a href="https://hackportal-jlpyiftuj-acmutd.vercel.app/about/questions">Screenshot of /about/questions</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/zrRNT5eWNs5fqbClfscqzb9Rzwq05_Lh2ZrSt191_Pwb6r0C-yt5zp-cCIaTa6sbGy9XozU5bgmdfgpfoRXr-Q.png">(view full size)</a> |<a href="https://hackportal-jlpyiftuj-acmutd.vercel.app/admin">Screenshot of /admin</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/xtDj5bq8PUZTk2GYZgJ30NU9nZKU4g2uR0ZW8kUUFWmCUmYEJ9Uqdr7C2yvjf2ia7fuhABIRiM4ETdOT9O1vFg.png">(view full size)</a> |



| [**…n/resolve/\[questionId\]**](https://hackportal-jlpyiftuj-acmutd.vercel.app/admin/resolve/[questionId]) | [**/admin/users**](https://hackportal-jlpyiftuj-acmutd.vercel.app/admin/users) |
|:-:|:-:|
|<a href="https://hackportal-jlpyiftuj-acmutd.vercel.app/admin/resolve/[questionId]">Screenshot of /admin/resolve/[questionId]</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/Lw_nLap_LHLlEw06QGZvAmBttwpoqk67Bj_ldTKnxxyBaTY89cBzy9ZTq4yJ72FSI4BFpyQ7P3qdfTMZJK8YLA.png">(view full size)</a> |<a href="https://hackportal-jlpyiftuj-acmutd.vercel.app/admin/users">Screenshot of /admin/users</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/qY5p0ybV8od5RKgDtbO0_b9zjMUfH7vQKzn-KXPRhQDToVGo4hHcl9y5vMl-fsFzMuJ29zoX3NVwg0TTw71FRg.png">(view full size)</a> |



And 24 other routes:
- [**/api/announcements**](https://hackportal-jlpyiftuj-acmutd.vercel.app/api/announcements)
- [**/api/applications**](https://hackportal-jlpyiftuj-acmutd.vercel.app/api/applications)
- [**/api/members**](https://hackportal-jlpyiftuj-acmutd.vercel.app/api/members)
- [**/api/questions**](https://hackportal-jlpyiftuj-acmutd.vercel.app/api/questions)
- [**/api/questions/pending/\[questionId\]**](https://hackportal-jlpyiftuj-acmutd.vercel.app/api/questions/pending/[questionId])
- [**/api/questions/pending**](https://hackportal-jlpyiftuj-acmutd.vercel.app/api/questions/pending)
- [**/api/resume/upload**](https://hackportal-jlpyiftuj-acmutd.vercel.app/api/resume/upload)
- [**/api/tokens**](https://hackportal-jlpyiftuj-acmutd.vercel.app/api/tokens)
- [**/api/userinfo**](https://hackportal-jlpyiftuj-acmutd.vercel.app/api/userinfo)
- [**/api/users**](https://hackportal-jlpyiftuj-acmutd.vercel.app/api/users)
- [**/dashboard/Components/AnnouncementCards**](https://hackportal-jlpyiftuj-acmutd.vercel.app/dashboard/Components/AnnouncementCards)
- [**/dashboard/Components/DocLinks**](https://hackportal-jlpyiftuj-acmutd.vercel.app/dashboard/Components/DocLinks)
- [**/dashboard/Components/MentorCard1**](https://hackportal-jlpyiftuj-acmutd.vercel.app/dashboard/Components/MentorCard1)
- [**/dashboard/Components/MentorCard3**](https://hackportal-jlpyiftuj-acmutd.vercel.app/dashboard/Components/MentorCard3)
- [**/dashboard/Components/Sidebar**](https://hackportal-jlpyiftuj-acmutd.vercel.app/dashboard/Components/Sidebar)
- [**/dashboard/Components/SpotlightCard**](https://hackportal-jlpyiftuj-acmutd.vercel.app/dashboard/Components/SpotlightCard)
- [**/dashboard/Components/SpotlightCardScroll**](https://hackportal-jlpyiftuj-acmutd.vercel.app/dashboard/Components/SpotlightCardScroll)
- [**/dashboard/hackerpack**](https://hackportal-jlpyiftuj-acmutd.vercel.app/dashboard/hackerpack)
- [**/dashboard**](https://hackportal-jlpyiftuj-acmutd.vercel.app/dashboard)
- [**/dashboard/scan-in**](https://hackportal-jlpyiftuj-acmutd.vercel.app/dashboard/scan-in)
- [**/dashboard/submit**](https://hackportal-jlpyiftuj-acmutd.vercel.app/dashboard/submit)
- [**/**](https://hackportal-jlpyiftuj-acmutd.vercel.app/)
- [**/profile**](https://hackportal-jlpyiftuj-acmutd.vercel.app/profile)
- [**/register**](https://hackportal-jlpyiftuj-acmutd.vercel.app/register)



Commit 950899d940530bdbc8568652b4c95a7ed89dfbec (https://hackportal-jlpyiftuj-acmutd.vercel.app).

**Review by abdullah50053 — APPROVED** [review]
Good for 0.1.0

**Comment by nam-t24** [comment]
There are some changes that would end up deleting and replacing some of the code that should be used in the final products. The smartphone nav(in app header) was deleted and replaced with a dropdown in this pr but the smartphone nav should ultimately be used.

**Review by abdullah50053 — DISMISSED** [review]
Mobile menu fixed.

**Review by nam-t24 — APPROVED** [review]

**Review by abdullah50053 — APPROVED** [review]
Still need to fix admin user dashboard mobile view and add submenus in mobile AppHeader

**Pull request merged**
