### PR TITLE
feat: Added feature to filter stats at a glance by user type

### LINKED ISSUE #115: [Feature] Add ability to include/exclude groups from stats
# Overview

Currently, the admin-side Stats at a Glance page displays the information of all users of HackPortal. This limits the information hackathon organizers have in regards to how many _hackers_ got swag or food or what their demographics were, instead of anyone with an account or organizer info being added to the data.

# Proposal

There should be options to include/disclude certain people's stats from showing up in the data. 
The options should include Admin, Super Admin, Hacker (these are people who have checked in and are not admin), and all accounts. 

# Supplemental Information

Example of issue:
141 hackers checked in (no way to differentiate checked-in admins from hackers).
Screen Shot 2022-04-15 at 6 11 00 PM

Organizers may want info on just hackers who have checked in, not everyone with an account. This is an example of the data being displayed for everyone with an account.
Screen Shot 2022-04-15 at 6 11 57 PM

### PR DESCRIPTION
**Pull request by DedsecKnight**
Implemented feature to allow super admins to filter stats at a glance by user
permissions (only hackers, admin, etc).

BREAKING CHANGE: Changed configuration of GeneralStats data type and data
returned by /api/stats

resolves #115

**UPDATE**: Added required changes. Currently, non check-in hackers are classified in Stats at a Glance as "Illegal Hacker" (because it is shorter than Non Check-in), but there are likely better name for this category.

### CODE REVIEW

**Review by nam-t24 — DISMISSED** [review]

**Comment by abdullah50053** [comment]
Add filter for "Checked in"

**Comment by abdullah50053** [comment]
"illegal hackers" includes admins and super admins, who usually don't check in anyways. We can drop that category completely.

**Comment by abdullah50053** [comment]
Add a "Checked in" option under "Filter Stats by"

**Comment by DedsecKnight** [comment]
Currently, "Hacker" represents checked-in hackers (non check-in hackers are completely ignored in the backend). Unless I misunderstood the intention, I can rename the "Hacker" to "Checked-in Hacker" if necessary.

**Review by MichaelZhao21 — APPROVED** [review]
There are things that need to be fixed in terms of code quality but it works; we'll fix it later

**Review by nam-t24 — APPROVED** [review]

**Comment by MichaelZhao21** [comment]
The issue with this PR is that we've switched to Nivo, so there's like hella conflicts uhhhhhhhhhhhhhhhhhh @DedsecKnight idk if you want to reimplement this in Nivo with a new PR or just fix the conflicts in this one (but the first might be easier)

**Comment by MichaelZhao21** [comment]
Closing this issue due to the fact that we completely changed the library that was used for this PR and thus making hella merge conflicts

**Pull request closed without merging**
