### PR TITLE
feat(home): Redesign Home Page & fix(fonts): Fonts not showing the right style

### PR DESCRIPTION
**Pull request by thetechie7**
Updated the UI for the Home Page from Figma.

In the previous PR (#181) I made, I forgot to include the new font files (sorry abt
that), which messed with the site's styling. I was told to include it in this PR instead of making a new one.

### CODE REVIEW

**Review by MichaelZhao21 — DISMISSED** [review]

**Comment by MichaelZhao21** [comment]
hi geeth can u change the header to be more bold

**Comment by abdullah50053** [comment]
The challenge arrows on mobile are messed up. Also, the keynote speaker descriptions don't show the bottom.

**Comment by thetechie7** [comment]
@abdullah50053 they are temporary as kelly didn't find the design yet for them.

**Comment by abdullah50053** [comment]
First FAQ is centered, others are left aligned.
Screenshot 2023-01-26 at 6 59 33 PM

Reduce gap between "meet the team" title and content:
Screenshot 2023-01-26 at 7 00 44 PM

**Comment by thetechie7** [comment]
fixed the issues

**Comment by thetechie7** [comment]
> image
> 
> 
> 
> This is negative mobile accessibility rizz :(( It's hard to see the left/right buttons plus it overlaps with the text.

i'll remove the arrows on mobile

**Comment by MichaelZhao21** [comment]
wait but if we remove arrows on mobile then ppl wont know to swipe which means negative UX accessibility rizz

**Comment by thetechie7** [comment]
i will make it look like this...
Screenshot 2023-02-09 at 12 51 20 PM

**Comment by MichaelZhao21** [comment]
that's W accessibility rizz

**Review by MichaelZhao21 — APPROVED** [review]

**Pull request merged**
