### PR TITLE
refactor: Improved typings for statRecordTypes

### PR DESCRIPTION
**Pull request by DedsecKnight**
This might not be the most ideal solution as organizers still have to manually add/remove the field name into one the following array for the `statRecordTypes` type to work properly: 

- `stringSingleField`
- `numberSingleField`
- `stringArrayField`
- `numberArrayField`

Another solution would be to do something similar to Prisma, in which we will have a standalone script that will read the config file and generate a `.ts` file containing the types.

### CODE REVIEW

**Comment by DedsecKnight** [comment]
The newest commit contains a script that will read in the config file and generate a type definition file for the stat records and registration object.

**Comment by DedsecKnight** [comment]
Documentation on the script-generated type definition feature of Hackportal **(consider adding this to HackPortal main documentation directory)**: 

- Run `npm run type:generate` to generate type definition based on the most recent version of the config file. For this branch, this command is configured to run before `npm run dev` and `npm run build`. 
- Generated types will be stored in `node_modules/@generated/types.ts`, which will allow better understanding of how the types are generated. The following is an example on how to import the generated type definition: 
```ts
import { Registration } from '@generated/types'
```
- Currently, the questions in the config file are divided into the following groups: 
    - **Single field**: Fields that expect user's manual input (further categorized based on expected data types). The data type of fields that fall in this category will be based on the question's expected data type (string or number). 
    - **Multiple choice field**: Fields that provide user a limited number of options to choose from. The data type of fields that fall in this category will be enum that is equivalent to the available options. 
    - **Checkbox fields**: Fields that allow user choose multiple options among a limited number of options. The data type of fields falling into this category will be an array accepting enum values equivalent to available options. 

If anyone have any questions about this feature, feel free to follow up in this PR and I will update this documentation section accordingly.

**Comment by abdullah50053** [comment]
@DedsecKnight:
Screen Shot 2022-08-22 at 6 34 08 PM

**Comment by abdullah50053** [comment]
the newest version is already in `feat/separate-registration` branch

**Pull request closed without merging**
