### PR TITLE
Fix/tags

### PR DESCRIPTION
**Pull request by NickBurnett**

### CODE REVIEW

**Comment by WillieCubed** [comment]
#### 📝 Changed routes:


| [**/admin/scan**](https://hackportal-3c4d1iuf2-acmutd.vercel.app/admin/scan) |
|:-:|
|<a href="https://hackportal-3c4d1iuf2-acmutd.vercel.app/admin/scan">Screenshot of /admin/scan</a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/GGaWnr79JnjCQbzXggi5ca91DY5wc3f8eeGdtI3z3ahg-UOEKizWYIEij7RubSr9iIqKmpZcB-TR_yWlO5alnQ.png">(view full size)</a> |







Commit ecdb932f540d6650bcf6098740453df35b11326c (https://hackportal-3c4d1iuf2-acmutd.vercel.app).

**Review by WillieCubed — COMMENTED** [review]
Can you describe exactly what you're doing here? It's not clear what these changes do.

**Comment by abdullah50053** [comment]
@WillieCubed prevents any random QR code to be scanned. All codes have hack appended to them

**Comment by NickBurnett** [comment]
> Can you describe exactly what you're doing here? It's not clear what these changes do.

Since there was no way to differentiate between a valid and invalid tag other than a tag being in the database, I added a simple format `hack:ID` so that they can be differentiated.

**Review by WillieCubed — APPROVED** [review]

**Pull request merged**
