### PR TITLE
fix(home page): Load home page when challenge data empty

### PR DESCRIPTION
**Pull request by ZzRanger**
Previously, if there are no challenges in the database, the website will crash.
This commit allows the website to run correctly even when there are no
challenges in db by providing dummy values to render on the client side.

### CODE REVIEW

**Review by DedsecKnight — DISMISSED** [review]
LGTM!

**Comment by abdullah50053** [comment]
Current implementation breaks the home page challenge display:

This PR:
Screen Shot 2022-04-21 at 11 18 52 PM

What it should look like:
Screen Shot 2022-04-21 at 11 20 04 PM

**Comment by DedsecKnight** [comment]
@ZzRanger it seems like you forgot this line when you edited the render logic:
```
setChallenges(sortedChallenges);
```
Refer to this for more details: https://github.com/acmutd/hackportal/blob/develop/pages/index.tsx#L69

**Comment by ZzRanger** [comment]
> @ZzRanger it seems like you forgot this line when you edited the render logic:
> 
> ```
> setChallenges(sortedChallenges);
> ```
> 
> Refer to this for more details: https://github.com/acmutd/hackportal/blob/develop/pages/index.tsx#L69

Thanks for pointing this out; I added that line back in my most recent commit.

**Comment by abdullah50053** [comment]
The issue still persists with only 1 challenge
Screen Shot 2022-04-25 at 1 30 23 AM

The ideal implementation would hide the "Challenges" section completely unless there was a challenge added in the backend.

**Pull request closed without merging**
