### PR TITLE
feat: Create dropdown menu for HackerPack mobile view

### LINKED ISSUE #147: [Chore] Make dropdown menu for HackerPack mobile view
# Overview
The current HackerPack menu on mobile is not user-friendly: 

Screen Shot 2022-06-21 at 11 30 53 PM

# Proposal
Redo the HackerPack mobile menu to make it more user-friendly according to the Figma designs.

# Supplemental Information
Figma designs: 

Screen Shot 2022-06-21 at 11 31 48 PM

The user clicks on category and is directed to Tech Workshop
Screen Shot 2022-06-21 at 11 32 05 PM

### PR DESCRIPTION
**Pull request by MichaelZhao21**
Fixes #147 

### Feature Description

Menu is fixed at the top of the page, with enough width allocated to show the collapsed menu. Small arrows on the side of the component allow for users to open and close sub-menus. The entire menu collapses when the user selects a section to navigate to.

### Extra Comments

* Fixed an issue where tailwind typo (`md:wd-5/6`) broke the page at medium width
* We should consider upgrading to tailwind v3, which contains many new features such as [scroll-padding](https://tailwindcss.com/docs/scroll-padding) -- this allows us to replace `before:content-[''] before:block before:h-36 before:-mt-36` with `scroll-pt-36`. We need one of these for each element that we navigate to using the anchor tag (eg. `#Section1`) because the default behavior is to bring that element to the top of the screen, which would be obscured by the fixed components (Appbar and Dropdown menu).
* Also extracted sidebar data to a JSON file (kind of addresses some of the comments in #149)

### Images

Collapsed:

image

Expanded:

image

### CODE REVIEW

**Comment by abdullah50053** [comment]
Bug: Site navigation options are under the page nav options
Screen Shot 2022-06-25 at 11 05 29 PM

**Comment by abdullah50053** [comment]
Also, it's probably better if the page nav bar is not sticky.

**Comment by MichaelZhao21** [comment]
Should the main sections even be clickable? It could potentially make clicking to expand the sub-sections confusing. Here's the updated design for the menu, where only the arrows on the right side will expand the drop downs:

image

**Comment by MichaelZhao21** [comment]
Also a small "return to top" button could be useful if the nav bar is not sticky

**Pull request closed without merging**
