### PR TITLE
fix(dashboard): Added sign-in message to the dashboard

### LINKED ISSUE #103: [Bug] : Dashboard visible without being signed in
### What did you expect to happen?

Dashboard should be hidden when signed out

### What happened?

Dashboard is visible when signed out

### Scope

Profile

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by NickBurnett**
fix #103

### CODE REVIEW

**Comment by nam-t24** [comment]
Should have a sign in message or a redirect to home page because with the new app header, the only way a non signed in user would get into dashboard would be if they typed in /dashboard in the url themselves

**Comment by NickBurnett** [comment]
> Should we have a sign in message or a redirect to home page because with the new app header, the only way a non signed in user would get into dashboard would be if they typed in /dashboard in the url themselves

It looks like the dashboard is available through the UI as well. Up to you, we can redirect.

**Comment by abdullah50053** [comment]
> > Should we have a sign in message or a redirect to home page because with the new app header, the only way a non signed in user would get into dashboard would be if they typed in /dashboard in the url themselves
> 
> It looks like the dashboard is available through the UI as well. Up to you, we can redirect.

The idea behind the navigation changes was that the Dashboard would be hidden unless the user is signed in, same goes for everything under the Dashboard. The user should not have access to "Day of" info unless they are signed in/part of the hackathon.
HackerPack got promoted b/c a user doesn’t need to be signed in to see the HackerPacks, same way they wouldn’t need to be signed in to see the schedule.

**Comment by NickBurnett** [comment]
> > > Should we have a sign in message or a redirect to home page because with the new app header, the only way a non signed in user would get into dashboard would be if they typed in /dashboard in the url themselves
> 
> > 
> 
> > It looks like the dashboard is available through the UI as well. Up to you, we can redirect.
> 
> 
> 
> The idea behind the navigation changes was that the Dashboard would be hidden unless the user is signed in, same goes for everything under the Dashboard. The user should not have access to "Day of" info unless they are signed in/part of the hackathon.
> 
> HackerPack got promoted b/c a user doesn’t need to be signed in to see the HackerPacks, same way they wouldn’t need to be signed in to see the schedule.

Ah ok, I'll deal with that when I get home then.

**Comment by NickBurnett** [comment]
Closing until the issue is more explicit.

**Pull request closed without merging**
