### PR TITLE
feat: Implemented new challenge view

### PR DESCRIPTION
**Pull request by DedsecKnight**
~Will make PR ready for review after every other components of new home page is ready.~

### CODE REVIEW

**Review by uy-seng — DISMISSED** [review]

**Review by vvyn — CHANGES_REQUESTED** [review]
image

It looks find on my laptop screen, but this is what it looks like on my monitor. You may want to add some padding or space to the right of the titles and descriptions.

**Review by vvyn — DISMISSED** [review]
Looks good👍

**Review by raywa04 — COMMENTED** [review]
Everything looks good! Something optional however is the spacing on the mobile view. image Right side has more space than left side.

**Review by raywa04 — APPROVED** [review]
lgtm!

**Pull request merged**
